### ISSUE TITLE
All info/cards dissappeared

### ISSUE THREAD

**Issue by Braderz87** [MKT-Playbook/Hub#11]
**Describe the bug**
_A clear and concise description of what the bug is._ All of my D/K/G cards have suddenly dissappeared. I’ve tried resetting the app and my phone, but the app remains clear, asking me to add cards. 

**To Reproduce**
_Steps to reproduce the behavior:_
1. _Go to '...'_
2. _Click on '....'_
3. _Scroll down to '....'_
4. _See error_

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Video**
_If applicable, add a link to a video (e.g. YouTube or Vimeo) to help explain your problem._

**Smartphone (please complete the following information):**
 - Version: [e.g. 1.1.8 (47)]
 - Jailbroken: [YES or NO]

**Additional context**
_Add any other context about the problem here._

**Comment by TitusPosiadly** [comment]
Hey thanks for the report. Could you add a bit more information regarding your device and the app version you are running?

    Device: [e.g. iPhone6]
    OS: [e.g. iOS8.1]
    Version: [e.g. 1.1.8 (47)]
    Jailbroken: [YES or NO]

**Comment by Braderz87** [comment]
Hello! Thanks for the response. 

Yes.

Device: iPhone XR
OS: iOS 14.8
Version: 1.2.0 (55)
Jailbroken: No

>

**Comment by TitusPosiadly** [comment]
Perfect, thanks.
Do you remember what you did right before everything disappeared or if anything unusual happened (For example did you see any error messages in the app)?

**Comment by Braderz87** [comment]
Hello,

No, I don’t remember an error or anything that may have warned me. Would you recommend deleting the app and redownloading?

Thanks again!

>

**Comment by TitusPosiadly** [comment]
When opening the card list do you see all the cards just without the level, points, and images or is the list completely empty? Also, did you recently download/open the app on another device that is connected to the same AppleID?

I can't really give you a good suggestion on what do to before I know what caused this. Very sorry and also sorry for the inconvenience this causes. It sounds like a very serious issue so I would like to make sure there isn't a simple fix before taking drastic measures. Oh, and did you have the database filled already with all your data/Do you still have recent screenshots of your inventory? I am asking to know how careful we have to be proceeding forward.

**Comment by TitusPosiadly** [comment]
Closed the issue due to inactivity. Without more info, I was unable to pinpoint the cause. If additional info comes up or if this issue occurs again for another user feel free to reopen this issue.
