### ISSUE TITLE
Crash when opening cards with points above the fourth cap

### ISSUE THREAD

**Issue by MusicIsTheBest** [MKT-Playbook/Hub#12]
**Describe the bug**
When I jump to the Paper Glider card, the app closes. Only that card. It's set at lvl 8 400 points right now.

**To Reproduce**
_Steps to reproduce the behavior:_
From any feature that gets you to a card it'll crash. Haven't tried from TOUR but selecting Paper Glider crashes the app from CARDS and TRACKS menus.

**Expected behavior**
It's pretty much at that value now so the app just won't let me edit the card. 

**Screenshots**

**Video**
_If applicable, add a link to a video (e.g. YouTube or Vimeo) to help explain your problem._

**Smartphone (please complete the following information):**
 - Device iPhone SE
 - OS: 16.0.3
 - Version: 2nd generation
 - Jailbroken: NO
**Additional context**
MKTP is 1.2.0

**Comment by TitusPosiadly** [comment]
Haha, what a strange bug. I just tested it and with level 8, 380 pts everything was fine. Even on 408, but as soon as I entered 400 I crashed as well. I will look into it shortly and will keep you posted. Thx for the report btw

**Comment by TitusPosiadly** [comment]
I found the issue. I forgot to adjust something with the new points cap. Will be fixed in v1.2.1.
