### ISSUE TITLE
“New Best” ranking seems incorrect for the Mii characters

### ISSUE THREAD

**Issue by joe-davenport** [MKT-Playbook/Hub#17]
**Describe the bug**
Many of the Mii characters are ranked at the bottom of the New Best sort, and I can see that many should be ranking near the top. 

**To Reproduce**
_Steps to reproduce the behavior:_
1. _Go to Cards > Driver > Sort as: By New Best
(The sort selection should also have an indicator)

![EFF4BC2C-205C-4B1D-8AD8-F35B650A150C](https://user-images.githubusercontent.com/19486607/205184655-19a00e6c-a7a3-4e54-bb63-bd84af8c2918.png)
![EF4FBBA9-F333-4B7A-903D-35BBF513E68E](https://user-images.githubusercontent.com/19486607/205184674-dd41b6be-75f6-41f5-bf1d-223ff67a1c1b.png)

**Comment by TitusPosiadly** [comment]
Hmm not sure I understood your issue. It seems to be working as intended. Maybe there is a slight confusion with the explanation for the "New Best" sort option? Let me summarize: The "New Best" sort option only refers to the number of best tracks the specific card will gain on the next level up. So for the yellow mii racing suit - how many tracks it will gain as best tracks when it's upgraded to level 2. In this case 0.

**Comment by joe-davenport** [comment]
Yes. I misunderstood the feature, I’ve been using it to decide the best place to send resources, but was thinking that it was the best overall rather than most one-level increase.

A sort to determine best use of “#” tickets seems like could be helpful.

My general plan is to keep sending tickets at the Mii and metallic/coin things.

On Dec 1, 2022, at 4:24 PM, Titus Posiadly ***@***.***> wrote:

﻿

Hmm not sure I understood your issue. It seems to be working as intended. Maybe there is a slight confusion with the explanation for the "New Best" sort option? Let me summarize: The "New Best" sort option only refers to the number of best tracks the specific card will gain on the next level up. So for the yellow mii racing suit - how many tracks it will gain as best tracks when it's upgraded to level 2. In this case 0.
