### ISSUE TITLE
Course pages lagging 

### ISSUE THREAD

**Issue by Terrance113** [MKT-Playbook/Hub#24]
The course pages are lagging and taking forever to go through each course and the variants tabs.

**Comment by TitusPosiadly** [comment]
Hey there, thanks for the report. Yeah, I noticed that as well a while ago and am working on a fix in the little time I have right now. Unfortunately, this isn't as easy of a fix as I had hoped. I need to rewrite a lot of code of the base structure of the app, but I'm on it.
