### ISSUE TITLE
Any hidden factor that decides which driver is the best option?

### ISSUE THREAD

**Issue by kdurov** [MKT-Playbook/Hub#27]
**Describe the bug**
I have two drivers at the same level same uncap and with exactly the same skill coin box . However one is shown as better while its size is smaller. 
Is there any hidden status that you use to decide which one trumps the others at the same level uncap and skill?

**To Reproduce**
_Steps to reproduce the behavior:_
open estimate score page

**Expected behavior**
Bigger driver should be superior.

**Screenshots**
[here is the screenshot](https://i.imgur.com/S7qPPQE.jpg)

**Comment by TitusPosiadly** [comment]
Hey, thanks for the report!
No, currently there are no hidden factors deciding which card is better when the score is the same. I think right now it just sorts it by the same sort key used in the Mario Kart Tour app. I was thinking about changing the number of coins obtainable on a track depending on the driver and kart size and changing the score that way depending on the size (adding coins for big d/k and reducing coins for small ones) but I don't have the sizes for karts and my database for driver size is currently incomplete. I guess I could go through the database and at least add all driver sizes and either sort drivers with the same score by size or include the mentioned score calculator change just for the drivers.

Which one would you prefer?

**Comment by kdurov** [comment]
Hi.

No need to add coins for bigger items. it'll cause more trouble and confusion.
What could be done is to prioritize bigger items when other stats are the same. 

btw. there's a mii bug that I didnt open another ticket for. 
when adding multiple Mii at the same time. some newly added Mii will not get the correct boost point. old Mii are not affected.

**Comment by TitusPosiadly** [comment]
> No need to add coins for bigger items. it'll cause more trouble and confusion.
> What could be done is to prioritize bigger items when other stats are the same.

Ok, thank you. I will think about it some more and will implement a fix for the next version.

> btw. there's a mii bug that I didnt open another ticket for.
> when adding multiple Mii at the same time. some newly added Mii will not get the correct boost point. old Mii are not affected.

Hmm, interesting. Do you have any more information about what exactly is wrong? What points you got vs what points you expected?
