### ISSUE TITLE
Unnecessary display of recalculation warning when changing level progress

### ISSUE THREAD

**Issue by joe-davenport** [MKT-Playbook/Hub#28]
**Describe the bug**
_A clear and concise description of what the bug is._
Increasing a card's progress while not increasing the level will trigger the warning that a recalculation is needed. The recalculate flag should be reserved only for level increases. My sort is Best-On, but I don't think it matters which sort is chosen.

**To Reproduce**
_Steps to reproduce the behavior:_
1. _Go to '...'_
2. _Click on '....'_
3. _Scroll down to '....'_
4. _See error_

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Video**
_If applicable, upload (max 10MB or ~5 sec) or add a link to a video (e.g. YouTube or Vimeo) to help explain your problem._

**Smartphone (please complete the following information):**
 - Version: [e.g. 1.1.8 (47)]
 - Jailbroken: [YES or NO]

**Additional context**
_Add any other context about the problem here._

**Comment by TitusPosiadly** [comment]
Hey, thanks for letting me know.

Yes, I am currently reworking all calculations and this issue will be solved as well in the process. It shouldn't be an issue in the new version (1.3) anymore.
