### ISSUE TITLE
Normal Kart Progress

### ISSUE THREAD

**Issue by Glorblenaak** [MKT-Playbook/Hub#29]
**Describe the bug**
When entering 1 as the progress for a normal kart at lvl 1, it automatically changes it to 0

**To Reproduce**
1. Go to 'Cards'
2. Click on a normal kart
3. Change the level to 1
4. Change the progress to 1
5. App changes it to 0

**Expected behavior**
Progress should update to and stay as 1 instead of changing to 0

**Smartphone:**
 - Device: [iPhone SE]
 - OS: [iOS 15.5]
 - Version: [1.2.1 (56)]
 - Jailbroken: [NO]

**Comment by TitusPosiadly** [comment]
Hey, thank you so much for the bug report.

I found the issue and will fix it for the upcoming version.

Thanks for letting me know.

**Comment by Glorblenaak** [comment]
Thank you!
