### ISSUE TITLE
Maximum Mii card points during import is currently 1850 rather than 2030.

### ISSUE THREAD

**Issue by joe-davenport** [MKT-Playbook/Hub#31]
When importing Mii cards with points above 1850 a fake lower point total must be used to prevent error blocking the save. 

There is not a problem to edit the points higher after the import has completed.

**Comment by TitusPosiadly** [comment]
Hey, thanks for the report! Hmm, strange. I had a look at the code but can't figure out the issue. Might be a bit far-fetched but maybe the text recognition recognizes a different number. Could you post the original screenshot with which you had the issue?

**Comment by joe-davenport** [comment]
![image](https://user-images.githubusercontent.com/19486607/224116720-17bd9895-e9f5-4419-b01a-c065a73d74f2.png)

**Comment by joe-davenport** [comment]
![image](https://user-images.githubusercontent.com/19486607/224116802-4ee04dab-1866-4bab-b922-5a86a17d91ea.png)

**Comment by joe-davenport** [comment]
![image](https://user-images.githubusercontent.com/19486607/224116902-48cdbb0e-ff65-484e-bd57-8a1126227dea.png)

**Comment by joe-davenport** [comment]
During import, you can not satisfy the limits until a manually entered point value of 1850 or lower has been added.

**Comment by TitusPosiadly** [comment]
Alright, I figured it out. Will be fixed in the upcoming version. Thanks again for letting me know and for the screenshots.

**Comment by joe-davenport** [comment]
Thanks!
