### ISSUE TITLE
[BETA] Bowser not showing as favorite for ranked’s Bowser Castle 1R/T

### ISSUE THREAD

**Issue by Turbotastick** [MKT-Playbook/Hub#36]
**Describe the bug**
I’m using level 7/1080 Bowser for the second track in this week’s ranked. Playbook doesn’t seem to have Bowser boosted for this track - it’s suggested my level 3 Kamek, followed by level 5 Waluigi and a few others.
![762C4819-249A-4EA6-8B05-E3B5DFD0281E](https://user-images.githubusercontent.com/132479369/235967070-9b32a674-05e4-491b-971e-3a64570057b1.png)
![AE9D2FCE-EF82-4567-B751-41F6A5A7AB6E](https://user-images.githubusercontent.com/132479369/235967081-abefb0c3-9e31-42dc-9113-b484467dc3e2.png)

**To Reproduce**
_Steps to reproduce the behavior:_
1. _Go to '...'_
2. _Click on '....'_
3. _Scroll down to '....'_
4. _See error_

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Video**
_If applicable, upload (max 10MB or ~5 sec) or add a link to a video (e.g. YouTube or Vimeo) to help explain your problem._

**Smartphone (please complete the following information):**
 - Version: [e.g. 1.1.8 (47)]
 - Jailbroken: [YES or NO]

**Additional context**
_Add any other context about the problem here._

**Comment by TitusPosiadly** [comment]
Ah yes, I forgot to change one thing in the last Beta version. About to submit a new version that should fix the issue. Thanks for letting me know.
