### ISSUE TITLE
Ludwig Mii racing suite not showing on ranked Wii DK summit R/T

### ISSUE THREAD

**Issue by atisme82** [MKT-Playbook/Hub#45]
Ludwig Mii racing suite not showing on ranked Wii DK summit R/T

![IMG_9509](https://github.com/MKT-Playbook/Hub/assets/154492334/5908c4a1-bc3f-44c2-aaa2-af67e321f360)
![IMG_9507](https://github.com/MKT-Playbook/Hub/assets/154492334/5102b100-9200-4069-a566-b95d9f9f3665)

![IMG_9508](https://github.com/MKT-Playbook/Hub/assets/154492334/ec11ff1b-98d7-42fb-9ffb-df85cb8f17ba)
![IMG_9507](https://github.com/MKT-Playbook/Hub/assets/154492334/972f97c3-813f-4c45-92c2-b37c3ffd0305)

**To Reproduce**
_Steps to reproduce the behavior:_
1. _Go to '...'_
2. _Click on '....'_
3. _Scroll down to '....'_
4. _See error_

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Video**
_If applicable, upload (max 10MB or ~5 sec) or add a link to a video (e.g. YouTube or Vimeo) to help explain your problem._

**Smartphone (please complete the following information):**
 - Version: [e.g. 1.1.8 (47)]
 - Jailbroken: [YES or NO]

**Additional context**
_Add any other context about the problem here._

**Comment by TitusPosiadly** [comment]
Hey, thanks for the report.

Yeah, sorry my bad. Seems like I forgot to add the Miis as signatures for all the first tracks.
Everything should be working now though.

Let me know if there is anything else wrong.
