### ISSUE TITLE
Lost all my data

### ISSUE THREAD

**Issue by ghost** [MKT-Playbook/Hub#47]
**Describe the bug**
_A clear and concise description of what the bug is._

Today when I opened the app, the race tab didn’t show the best drivers/karts/gliders for the cups. Then I quit the app and restarted the app and all my data were gone :( I try to re-enter my data but the race tab still has a glitch.

**Smartphone (please complete the following information):**
 - Device: IPhone 13
 - OS: iOS 17.5.1
 - Version: [e.g. 1.1.8 (47)]
 - Jailbroken: NO

**Comment by TitusPosiadly** [comment]
Hey, thanks for reaching out. Could you send me the app log file either here or via email to info @ mkt-playbook.com? You can export the log file through the app settings, then scroll down and tap on "Export logs". Also, do you by any chance use multiple devices with the same Apple iCloud account?

**Comment by ghost** [comment]
Hello,I only use the app on my phone. Can I use it w/o icloud? Thanks Nathalie ThieryLe 10 juil. 2024 à 16:38, Titus Posiadly ***@***.***> a écrit :﻿
Hey, thanks for reaching out. Could you send me the app log file either here or via email to info @ mkt-playbook.com? You can export the log file through the app settings, then scroll down and tap on "Export logs". Also, do you by any chance use multiple devices with the same Apple iCloud account?

**Comment by TitusPosiadly** [comment]
Hmm, well yes you can use it without iCloud, but if you never used the app on another device, this will likely not be the source of the issue. Let me know when you get around to exporting the logs. Maybe those will provide me with a bit more info. Cheers Titus

**Comment by ghost** [comment]
Here’s the log Nathalie ThieryLe 10 juil. 2024 à 17:37, Titus Posiadly ***@***.***> a écrit :﻿
Hmm, well yes you can use it without iCloud, but if you never used the app on another device, this will likely not be the source of the issue. Let me know when you get around to exporting the logs. Maybe those will provide me with a bit more info. Cheers Titus

**Comment by TitusPosiadly** [comment]
Ah, I think the log files don't get transferred when you reply to a GitHub comment via email. You might have to manually upload the file on GitHub or send me a direct email to info@mkt-playbook.com

**Comment by ghost** [comment]
Thanks Just sent itNathalie ThieryLe 10 juil. 2024 à 18:03, Titus Posiadly ***@***.***> a écrit :﻿
Ah, I think the log files don't get transferred when you reply to a GitHub comment via email. You might have to manually upload the file on GitHub or send me a direct email to ***@***.***
