### ISSUE TITLE
Tour not updating - Anniversary Tour 2024

### ISSUE THREAD

**Issue by bbgs7161** [MKT-Playbook/Hub#49]
**Describe the bug**
No matter what i do, i cant get the tour to update from the Sundae tour 2024 to the anniversary tour 2024

**To Reproduce**
_Steps to reproduce the behavior:_
I have got to update public database, reloaded the content and it will just load the sunday tour 2024

**Expected behavior**
I expected like in the past the that tour would update to the current tour, it always has worked that way.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Video**
_If applicable, upload (max 10MB or ~5 sec) or add a link to a video (e.g. YouTube or Vimeo) to help explain your problem._

**Smartphone (please complete the following information):**
 - Device: iPhone 15 pro max
 - OS: 17
 - Version: 17.6.1
 - Jailbroken: No

**Comment by TitusPosiadly** [comment]
Hey, thanks for reaching out!

I’m currently in the process of updating the app to the Anniversary Tour 2024. The amazing folks behind the data mining, who kindly share the data with everyone every tour, took just a little longer this time, which caused a slight delay.

Good news though – the update will be ready within the next 1 or 2 hours! Usually, it takes around 12-24 hours, sometimes up to 48, for me to get everything ready for the next tour, but we're almost there now.

I really appreciate your patience and thanks again for your understanding!

**Comment by TitusPosiadly** [comment]
Alright! Everything is up to date again. Your app should update itself the next time you open it up.

Cheers, and happy driving ❤️
