### ISSUE TITLE
“By New Best” and “Best On” recalculation issues until manually loading the card

### ISSUE THREAD

**Issue by joe-davenport** [MKT-Playbook/Hub#52]
After a recalculation, in order to accurately sort the cards by the “By New Best” option you currently need to individually enter each card and wait 10+ seconds for the list to populate and the new data to refresh. 

By New Best will nearly always over estimate the tracks which will be added if a card is leveled up until visiting the individual card. Some Level 8 cards will also occasionally initially display that a new best could be achieved until the recalculation occurs. Maybe this bug is related to calculating some Level 9 card possibilities. 

By New Best may need to have its own recalculation. 

Best On also has some related calculation issues that will not cure until visiting the individual card and allowing the entire list to generate.

**Comment by TitusPosiadly** [comment]
Hmm, I thought I fixed this issue a while ago. If things were working correctly, the two calculations should use the same code, but you're right; for some reason, the result is still different. I will look into it and also look at the level 9 thing. Thanks for letting me know!

**Comment by joe-davenport** [comment]
If I allow the recalculation the previously fixed cards will revert to the wrong results and level 8 cards will have potential New Best tracks again until I enter each card and allow the individual calculation again. But manually entering each card takes a lot of time since it’s about 10 seconds on each even with a iPhone 16 Pro.

On Nov 1, 2024, at 10:25 AM, Titus Posiadly ***@***.***> wrote:

﻿

Hmm, I thought I fixed this issue a while ago. If things were working correctly, the two calculations should use the same code, but you're right; for some reason, the result is still different. I will look into it and also look at the level 9 thing. Thanks for letting me know!

**Comment by TitusPosiadly** [comment]
Fixed! Will be available on the AppStore shortly (version 1.3.7)
