### ISSUE TITLE
View only Normal, Super, or High-end

### ISSUE THREAD

**Issue by joe-davenport** [MKT-Playbook/Hub#53]
It would be nice to be able to sort the cards to only view the Normal or Super items when trying to determine the best candidates for upgrades. 

After a restore of the database, I don’t have all the images anymore, so it’s difficult to analyze the Normal and Super items now.

**Comment by TitusPosiadly** [comment]
Yeah, I think I can fairly easily add another filter for the search bar. Something like "t1", "t2", and "t3" or "normal", "super", "high-end" or "silver", "gold", "purple". Would those work? Or I can just change the default background color to reflect the rarity.

**Comment by joe-davenport** [comment]
You probably just need to add the field for them in the DETAILS at the bottom of the card.

[image0.png]

On Nov 1, 2024, at 10:11 AM, Titus Posiadly ***@***.***> wrote:

﻿

Yeah, I think I can fairly easily add another filter for the search bar. Something like "t1", "t2", and "t3" or "normal", "super", "high-end" or "silver", "gold", "purple". Would those work? Or I can just change the default background color to reflect the rarity.

**Comment by TitusPosiadly** [comment]
Can you manually add the image to GitHub? For some reason, the image won't be included when replying via email.

**Comment by joe-davenport** [comment]
It was just an image of the bottom of the individual card. You don’t have a field for Item Type or whatever you’d want to call the Normal Super and High-End. If that was a field entry the issue would be solved of analyzing a scenario of how to use a Super ticket upgrade without the other types displayed.

On Nov 1, 2024, at 5:14 PM, Titus Posiadly ***@***.***> wrote:

﻿

Can you manually add the image to GitHub? For some reason, the image won't be included when replying via email.

**Comment by TitusPosiadly** [comment]
Alright, I added all three. Will be available on the AppStore shortly (version 1.3.7)
